--liquibase formatted sql
--changeset annamalai.palanikumar:table_admin_dml_0.0.1
INSERT INTO admin (id, email) VALUES (1, 'me@annamalai.er.in');
INSERT INTO admin (id, email) VALUES (2, 'annamalai@outlook.in');
INSERT INTO admin (id, email) VALUES (3, 'annamalai10051996@gmail.com');
--rollback delete from admin where id in (1, 2, 3);

--changeset annamalai.palanikumar:table_portfolio_dml_0.0.1
INSERT INTO portfolio (id, about, address, company, country, email, face_book, git_hub, git_lab, google_developer, instagram, job, linked_in, mobile, name, stack_over_flow, twitter) VALUES (1, '{"ops":[{"attributes":{"color":"#272829","bold":true},"insert":"Passionate"},{"attributes":{"color":"#272829"},"insert":" and efficient "},{"attributes":{"color":"#272829","bold":true},"insert":"Full Stack"},{"attributes":{"color":"#272829"},"insert":" Developer with 5+ years of hands-on experience in "},{"attributes":{"color":"#272829","bold":true},"insert":"scalable application"},{"attributes":{"color":"#272829"},"insert":" development and maintenance"},{"attributes":{"color":"#272829"},"insert":" using different technologies and programming languages. Received "},{"attributes":{"color":"#272829","bold":true},"insert":"''Heroic Coding Award''"},{"attributes":{"color":"#272829"},"insert":" and "},{"attributes":{"color":"#272829","bold":true},"insert":"''Above and Beyond Award''"},{"attributes":{"color":"#272829"},"insert":" for developing software components of "},{"attributes":{"color":"#272829","bold":true},"insert":"Ecommerce Platform"},{"attributes":{"color":"#272829"},"insert":" with best "},{"attributes":{"color":"#272829","bold":true},"insert":"quality"},{"attributes":{"color":"#272829"},"insert":" from "},{"attributes":{"bold":true,"color":"#067ded","link":"https://www.infosysequinox.com/"},"insert":"Infosys Equinox(Former SKAVA, An Infosys Company)"},{"attributes":{"color":"#272829"},"insert":". In Infosys Equinox, I’ve built "},{"attributes":{"color":"#272829","bold":true},"insert":"e-commerce platform components"},{"attributes":{"color":"#272829"},"insert":" which can support placing more than "},{"attributes":{"color":"#272829","bold":true},"insert":"10 thousand orders per Minute"},{"attributes":{"color":"#272829"},"insert":"."},{"insert":"\\n"}]}', 'Värdshusvägen 6 B, 76430 Älmsta, Norrtälje, Stockholm, Sweden.', 'ComeOn!', 'Sweden', 'annamalai@outlook.in', 'https://www.facebook.com/annamalai.palanikumar.be', 'https://github.com/annamalai-palanikumar', 'https://gitlab.com/annamalai-palanikumar', 'https://g.dev/annamalai-palanikumar', 'https://www.instagram.com/mistermalai', 'Full Stack Developer', 'https://www.linkedin.com/in/annamalai-p', '+46790123327', 'Annamalai Palanikumar', 'https://stackoverflow.com/users/6784846', 'https://twitter.com/mistermalai');
--rollback delete from portfolio where id in (1);